backend:
  name: git-gateway
  branch:

publish_mode: editorial_workflow
media_folder: "/public/images/posts"
public_folder: "/images/posts"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "tytuł", name: "title", widget: "string"}
      - {label: "data publikacji", name: "pubDate", widget: "datetime", date_format: "DD.MM.YYYY", timeFormat: false}
      - {label: "opis", name: "description", widget: "string"}
      - {label: "zdjęcie główne", name: "heroImage", widget: "image"}
      - {label: "tekst", name: "body", widget: "markdown"}